heat_template_version: 2014-10-16

parameters:

  overcloud_flavor:
    type: string

  overcloud_image:
    type: string

  key_name:
    type: string

  overcloud_name:
    type: string

  private_net:
    type: string

  overcloud_user_data:
    type: string

  overcloud_user_data_format:
    type: string

resources:
  overcloud_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: overcloud_sg
      description: Ping and SSH
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

  overcloud_node:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: overcloud_flavor}
      image: {get_param: overcloud_image}
      config_drive: false
      key_name: {get_param: key_name}
      user_data: {get_param: overcloud_user_data}
      user_data_format: {get_param: overcloud_user_data_format}
      networks:
        - {network: {get_param: private_net}}
      security_groups:
        - "default"
        - {get_resource: overcloud_sg}
      name: {get_param: overcloud_name}
      software_config_transport: POLL_SERVER_HEAT

outputs:

  overcloud_node:
    description: "overcloud node resource"
    value: {get_resource: overcloud_node}
  overcloud_private_ip:
    description: "private ip of the overcloud instance"
    value:
      get_attr:
        - overcloud_node
        - networks
        - {get_param: private_net}
        - 0
