heat_template_version: 2014-10-16

description: Template for deploying overcloud nodes.  Can be wrapped in a ResourceGroup for scaling.

parameters:

  overcloud_flavor:
    type: string
    default: overcloud
    description: Recommended to be at least 1 vcpu, 4 GB RAM, 50 GB disk

  overcloud_image:
    type: string
    default: empty
    description: The base image to use for overcloud instances

  key_name:
    type: string
    default: default
    description: Nova keypair to inject into the undercloud and bmc

  overcloud_node_count:
    type: number
    default: 1
    description: Number of overcloud nodes to deploy

  private_net_admin:
    type: string
    default: private
    description: Name of a private network which can have floating ips associated with it

  private_subnet_admin:
    type: string

  private_net_cluster1:
    type: string
    default: private1
    description: Name of a private cluster network 1 which has no floating ips associated

  private_subnet_cluster1:
    default: private1
    type: string

  private_net_cluster2:
    type: string
    default: private2
    description: Name of a private cluster network 2 which has no floating ips associated

  private_subnet_cluster2:
    default: private2
    type: string

  private_net_cluster3:
    type: string
    default: private3
    description: Name of a private cluster network 3 which has no floating ips associated

  private_subnet_cluster3:
    default: private3
    type: string

  overcloud_name:
    type: string
    default: overcloud
    description: Name of the overcloud instances. The name will be prefixed with the stack name.

  sg:
    type: string
    default: ''
    description: Neutron sec group

  overcloud_user_data:
    type: string

resources:

  overcloud_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: overcloud_node_count}
      resource_def:
        type: OS::TraaS::OvercloudNode
        properties:
          overcloud_flavor: {get_param: overcloud_flavor}
          overcloud_image: {get_param: overcloud_image}
          key_name: {get_param: key_name}
          private_net_admin: {get_param: private_net_admin}
          private_subnet_admin: {get_param: private_subnet_admin}
          private_net_cluster1: {get_param: private_net_cluster1}
          private_subnet_cluster1: {get_param: private_subnet_cluster1}
          private_net_cluster2: {get_param: private_net_cluster2}
          private_subnet_cluster2: {get_param: private_subnet_cluster2}
          private_net_cluster3: {get_param: private_net_cluster3}
          private_subnet_cluster3: {get_param: private_subnet_cluster3}
          overcloud_user_data: {get_param: overcloud_user_data}
          sg: {get_param: sg}
          overcloud_name:
            list_join:
              - '-'
              - - {get_param: overcloud_name}
                - '%index%'


outputs:
