heat_template_version: 2014-10-16

description: Template for deploying overcloud nodes.  Can be wrapped in a ResourceGroup for scaling.

parameters:

  overcloud_flavor:
    type: string
    default: overcloud
    description: Recommended to be at least 1 vcpu, 4 GB RAM, 50 GB disk

  overcloud_image:
    type: string
    default: empty
    description: The base image to use for overcloud instances

  key_name:
    type: string
    default: default
    description: Nova keypair to inject into the undercloud and bmc

  overcloud_node_count:
    type: number
    default: 1
    description: Number of overcloud nodes to deploy

  private_net:
    type: string
    default: private
    description: Name of a private network which can have floating ips associated with it

  overcloud_name:
    type: string
    default: overcloud
    description: Name of the overcloud instances. The name will be prefixed with the stack name.

  default_sg:
    type: string
    default: all_sg

  overcloud_user_data:
    type: string
    default: ""
    description: Userdata to inject into the overcloud instance

  overcloud_user_data_format:
    type: string
    default: SOFTWARE_CONFIG
    description: Userdata format for the overcloud instance

resources:

  overcloud_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: overcloud_node_count}
      resource_def:
        type: OS::TraaS::OvercloudNode
        properties:
          overcloud_flavor: {get_param: overcloud_flavor}
          overcloud_image: {get_param: overcloud_image}
          key_name: {get_param: key_name}
          private_net: {get_param: private_net}
          overcloud_user_data: {get_param: overcloud_user_data}
          overcloud_user_data_format: {get_param: overcloud_user_data_format}
          overcloud_name:
            list_join:
              - '-'
              - - {get_param: overcloud_name}
                - '%index%'


outputs:
