heat_template_version: newton

parameters:

  undercloud:
    type: string
    description: Undercloud server resource

  undercloud_private_ip:
    type: string
    description: undercloud private ip address

  overcloud_nodes:
    type: json
    description: Overcloud server resources

  overcloud_private_ips:
    type: comma_delimited_list
    description: Overcloud node private ip addresses

  toci_jobtype:
    type: string
    default: multinode-1ctlr-featureset004
    description: tripleo-ci jobtype as parsed by toci_gate_test.sh

  tripleo_ci_remote:
    type: string
    default: "https://github.com/slagle/tripleo-ci"
    description: Git remote to use for tripleo-ci repository

  tripleo_ci_branch:
    type: string
    default: traas
    description: Git branch to use for tripleo-ci repository

  trass_repo:
    type: string
    default: "https://github.com/slagle/trass"
    description: Git remote to use for trass repository

  ci_changes:
    type: string
    default: ''
    description: A caret character separated list of the changes upon which
                 tripleo-ci, tripleo-quickstart, tripleo-quickstart-extra

  zuul_changes:
    type: string
    default: ''
    description: A caret character separated list of the changes upon which
                 this build is dependent upon in the form of a colon character separated
                 list consisting of project name, target branch, and revision ref.

  zuul_branch:
    type: string
    default: 'master'
    description: Which branch are we starting from.

resources:

  TociJobUndercloudConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash
        set -eux
        rm -rf /etc/profile.d/traas.sh
        echo export PRIMARY_NODE_IP=\"$PRIMARY_NODE_IP\" >> /etc/profile.d/traas.sh
        echo export SUB_NODE_IPS=\"$SUB_NODE_IPS\" >> /etc/profile.d/traas.sh
        echo export TOCI_JOBTYPE=\"$TOCI_JOBTYPE\" >> /etc/profile.d/traas.sh
        echo export ZUUL_CHANGES=\"$ZUUL_CHANGES\" >> /etc/profile.d/traas.sh
        echo export CI_CHANGES=\"$CI_CHANGES\" >> /etc/profile.d/traas.sh
        echo export TRIPLEO_CI_REMOTE=\"$TRIPLEO_CI_REMOTE\" >> /etc/profile.d/traas.sh
        echo export TRIPLEO_CI_BRANCH=\"$TRIPLEO_CI_BRANCH\" >> /etc/profile.d/traas.sh
        echo export ZUUL_BRANCH=\"$ZUUL_BRANCH\" >> /etc/profile.d/traas.sh
        mkdir -p /etc/nodepool
        if [ ! -f /etc/nodepool/id_rsa ]; then
          ssh-keygen -t rsa -f /etc/nodepool/id_rsa
        fi
        cp /etc/nodepool/id_rsa* /home/centos/.ssh
        cat /etc/nodepool/id_rsa.pub >> /home/centos/.ssh/authorized_keys
        chown -R centos.centos /home/centos /etc/nodepool
        mkdir -p $heat_outputs_path
        cp /etc/nodepool/id_rsa.pub $heat_outputs_path.public_key
      inputs:
        - name: PRIMARY_NODE_IP
          type: String
          description: IP address of primary node (Undercloud)
        - name: SUB_NODE_IPS
          type: String
          description: IP addresses of sub nodes (Overcloud nodes). Space separated list.
        - name: TOCI_JOBTYPE
          type: String
          description: tripleo-ci jobtype as parsed by toci_gate_test.sh
        - name: ZUUL_CHANGES
          type: String
          description: ZUUL_CHANGES variable containing patches to be tested in toci job
        - name: ZUUL_BRANCH
          type: String
          description: ZUUL_BRANCH which branch we want to start from
        - name: CI_CHANGES
          type: String
          description: CI_CHANGES variable containing patches for boostraping oooq
        - name: TRIPLEO_CI_REMOTE
          type: String
          description: Git remote to use for tripleo-ci repository
        - name: TRIPLEO_CI_BRANCH
          type: String
          description: Git branch to use for tripleo-ci repository
      outputs:
        - name: public_key
          description: public key
          type: String

  TociJobUndercloudDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: TociJobUndercloudConfig}
      server: {get_param: undercloud}
      signal_transport: HEAT_SIGNAL
      input_values:
        PRIMARY_NODE_IP: {get_param: undercloud_private_ip}
        SUB_NODE_IPS:
          list_join:
            - ' '
            - {get_param: overcloud_private_ips}
        TOCI_JOBTYPE: {get_param: toci_jobtype}
        TRIPLEO_CI_REMOTE: {get_param: tripleo_ci_remote}
        TRIPLEO_CI_BRANCH: {get_param: tripleo_ci_branch}
        ZUUL_CHANGES: {get_param: zuul_changes}
        ZUUL_BRANCH: {get_param: zuul_branch}
        CI_CHANGES: {get_param: ci_changes}

  DisconnectFromHostHeat:
    type: OS::Heat::Value
    properties:
      type: string
      value: |
        # Disconnect this Node from the host cloud's Heat
        systemctl stop os-collect-config
        rm -rf /var/lib/os-collect-config/*
        rm -rf /var/run/os-collect-config/*
        rm -rf /var/lib/cloud/data/cfn-init-data
        rm -f /var/lib/heat-cfntools/cfn-init-data
        mkdir /var/lib/os-collect-config/local-data
        echo '{ "os-collect-config": { "collectors": ["heat", "request", "local"], "command": "os-refresh-config" } }' > /var/lib/os-collect-config/local-data/00-os-collect-config
        rm -f /etc/os-collect-config.conf
        os-apply-config -m /var/lib/os-collect-config/local-data/00-os-collect-config

  TociJobOvercloudConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -eux
            echo $public_key >> /home/centos/.ssh/authorized_keys

            $disconnect_snippet
          params:
            $disconnect_snippet: {get_attr: [DisconnectFromHostHeat, value]}
      inputs:
        - name: public_key
          type: String
          description: public key

  TociJobOvercloudDeployment:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: [TociJobUndercloudDeployment]
    properties:
      config: {get_resource: TociJobOvercloudConfig}
      servers: {get_param: overcloud_nodes}
      signal_transport: HEAT_SIGNAL
      input_values:
        public_key: {get_attr: [TociJobUndercloudDeployment, public_key]}

  TociJobNodeExtraConfig:
    type: OS::TraaS::NodeExtraConfig
    depends_on: [TociJobOvercloudDeployment]
    properties:
      undercloud: {get_param: undercloud}
      overcloud_nodes: {get_param: overcloud_nodes}

  TociJobConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -eux

            $disconnect_snippet

            rpm -q git || yum -y install git
            su -l centos -c "git clone $trass_repo"
            su -l centos -c /home/centos/traas/scripts/traas.sh &

            # This is pretty hacky, meh.
            rpm -q psmisc || yum -y install psmisc
            killall -9 os-refresh-config
            killall -9 dib-run-parts
            exit 0
          params:
            $disconnect_snippet: {get_attr: [DisconnectFromHostHeat, value]}
            $trass_repo: {get_param: trass_repo}
      inputs:
        - name: PRIMARY_NODE_IP
          type: String
          description: IP address of primary node (Undercloud)
        - name: SUB_NODE_IPS
          type: String
          description: IP addresses of sub nodes (Overcloud nodes). Space separated list.
        - name: TOCI_JOBTYPE
          type: String
          description: tripleo-ci jobtype as parsed by toci_gate_test.sh
        - name: ZUUL_CHANGES
          type: String
          description: ZUUL_CHANGES variable containing patches to be tested in toci job
        - name: CI_CHANGES
          type: String
          description: CI_CHANGES variable containing patches to be applied at quickstart bootstrap
        - name: TRIPLEO_CI_REMOTE
          type: String
          description: Git remote to use for tripleo-ci repository
        - name: TRIPLEO_CI_BRANCH
          type: String
          description: Git branch to use for tripleo-ci repository

  TociJobDeployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: [TociJobNodeExtraConfig]
    properties:
      config: {get_resource: TociJobConfig}
      server: {get_param: undercloud}
      input_values:
        PRIMARY_NODE_IP: {get_param: undercloud_private_ip}
        SUB_NODE_IPS:
          list_join:
            - ' '
            - {get_param: overcloud_private_ips}
        TOCI_JOBTYPE: {get_param: toci_jobtype}
        TRIPLEO_CI_REMOTE: {get_param: tripleo_ci_remote}
        TRIPLEO_CI_BRANCH: {get_param: tripleo_ci_branch}
      signal_transport: NO_SIGNAL

outputs:
