heat_template_version: 2015-04-30

parameters:

  overcloud_flavor:
    type: string
    default: overcloud
    description: Nova flavor for overcloud instances. Recommended to be at least 4
                 vcpu, 8 GB RAM, 40 GB disk

  overcloud_image:
    type: string
    default: empty
    description: The base image to use for overcloud instances

  key_name:
    type: string
    default: default
    description: Nova keypair to inject into the undercloud and overcloud instances

  overcloud_node_count:
    type: number
    default: 2
    description: Number of overcloud instances to deploy

  private_net:
    type: string
    default: private
    description: Name of a private network which will be associated with all instances

  public_net:
    type: string
    default: public
    description: Name of the network to use for allocating a floating ip for the undercloud instance

  overcloud_name:
    type: string
    default: overcloud
    description: Name of the overcloud instances. The name will be prefixed with the stack name.

  undercloud_name:
    type: string
    default: undercloud
    description: Name of the undercloud instance. The name will be prefixed with the stack name.

  undercloud_flavor:
    type: string
    default: m1.large
    description: Nova flavor for the undercloud instance. Recommended to be at least 4
                 vcpu, 8 GB RAM, 40 GB disk

  undercloud_image:
    type: string
    default: CentOS-7-x86_64-GenericCloud-1503
    description: Image to boot as the undercloud instance

  undercloud_docker_registry_mirror:
    type: string
    default: ""
    description: A docker registry mirror

  toci_jobtype:
    type: string
    default: multinode-nonha-oooq
    description: tripleo-ci jobtype as parsed by toci_gate_test.sh

  zuul_changes:
    type: string
    default: ''
    description: A caret character separated list of the changes upon which
                 this build is dependent upon in the form of a colon character separated
                 list consisting of project name, target branch, and revision ref.

  tripleo_ci_remote:
    type: string
    default: "https://github.com/slagle/tripleo-ci"
    description: Git remote to use for tripleo-ci repository

  tripleo_ci_branch:
    type: string
    default: traas
    description: Git branch to use for tripleo-ci repository


resources:

  public_network:
    type: OS::TraaS::PublicNetwork
    properties:
      public_net: {get_param: public_net}

  private_network:
    type: OS::TraaS::PrivateNetwork
    properties:
      private_net: {get_param: private_net}

  user_data_script:
    type: OS::Heat::Value
    properties:
      type: string
      value: |
        #!/bin/bash
        rpm -q git || yum -y install git
        git clone https://git.openstack.org/openstack-infra/tripleo-ci
        export HOME=/root
        tripleo-ci/scripts/tripleo.sh --repo-setup
        yum -y install python-heat-agent*
        rm -f /etc/yum.repos.d/delorean*
        rm -rf tripleo-ci
        systemctl daemon-reload
        systemctl enable os-collect-config
        reboot

  undercloud:
    depends_on: [public_network]
    type: OS::TraaS::Undercloud
    properties:
      undercloud_flavor: {get_param: undercloud_flavor}
      undercloud_image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      undercloud_name:
        list_join:
          - '-'
          - - {get_param: 'OS::stack_name'}
            - {get_param: undercloud_name}
      undercloud_user_data: {get_attr: [user_data_script, value]}
      private_net: {get_attr: [private_network, private_net]}
      public_net: {get_attr: [public_network, public_net]}

  overcloud_nodes:
    type: OS::TraaS::OvercloudNodes
    depends_on: [private_network]
    properties:
      overcloud_flavor: {get_param: overcloud_flavor}
      overcloud_image: {get_param: overcloud_image}
      key_name: {get_param: key_name}
      overcloud_node_count: {get_param: overcloud_node_count}
      private_net: {get_attr: [private_network, private_net]}
      overcloud_user_data: {get_attr: [user_data_script, value]}
      overcloud_name:
        list_join:
          - '-'
          - - {get_param: 'OS::stack_name'}
            - {get_param: overcloud_name}

  toci_job:
    type: OS::TraaS::TociJob
    depends_on: [undercloud, overcloud_nodes]
    properties:
      undercloud: {get_attr: [undercloud, undercloud_server]}
      undercloud_private_ip: {get_attr: [undercloud, undercloud_private_ip]}
      undercloud_docker_registry_mirror: {get_param: undercloud_docker_registry_mirror}
      overcloud_nodes: {get_attr: [overcloud_nodes, resource.overcloud_nodes, attributes, overcloud_node]}
      overcloud_private_ips: {get_attr: [overcloud_nodes, resource.overcloud_nodes, overcloud_private_ip]}
      toci_jobtype: {get_param: toci_jobtype}
      zuul_changes: {get_param: zuul_changes}
      tripleo_ci_remote: {get_param: tripleo_ci_remote}
      tripleo_ci_branch: {get_param: tripleo_ci_branch}

outputs:
