heat_template_version: newton

parameters:
  undercloud_flavor:
    type: string
  undercloud_image:
    type: string
  key_name:
    type: string
  undercloud_name:
    type: string
  undercloud_user_data:
    type: string
  private_net_admin:
    type: string
  private_subnet_admin:
    type: string
  private_net_cluster1:
    type: string
  private_subnet_cluster1:
    type: string
  private_net_cluster2:
    type: string
  private_subnet_cluster2:
    type: string
  private_net_cluster3:
    type: string
  private_subnet_cluster3:
    type: string
  public_net:
    type: string
    default: ''
  sg:
    type: string
    description: Neutron sec group

resources:

  uc_admin_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_net_admin}
      fixed_ips:
        - subnet: {get_param: private_subnet_admin}
      security_groups:
        - {get_param: sg}

  uc_data_port1:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_net_cluster1}
      port_security_enabled: false
      fixed_ips:
        - subnet: {get_param: private_subnet_cluster1}

  uc_data_port2:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_net_cluster2}
      port_security_enabled: false
      fixed_ips:
        - subnet: {get_param: private_subnet_cluster2}

  uc_data_port3:
    type: OS::Neutron::Port
    properties:
      network: {get_param: private_net_cluster3}
      port_security_enabled: false
      fixed_ips:
        - subnet: {get_param: private_subnet_cluster3}

  undercloud_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: undercloud_flavor}
      image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      networks:
        - {port: {get_resource: uc_data_port1}}
        - {port: {get_resource: uc_data_port2}}
        - {port: {get_resource: uc_data_port3}}
        - {port: {get_resource: uc_admin_port}}
      name: {get_param: undercloud_name}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_param: undercloud_user_data}
      software_config_transport: POLL_SERVER_HEAT

  undercloud_floating_ip:
    type: OS::TraaS::UndercloudFloating
    properties:
      public_net: {get_param: public_net}
      undercloud_port:
        get_attr:
          - undercloud_server
          - addresses
          - {get_param: private_net_admin}
          - 0
          - port

  undercloud_swap:
    type: OS::TraaS::Swap
    properties:
      server: {get_resource: undercloud_server}

outputs:
  undercloud_server:
    description: "undercloud server resource"
    value: {get_resource: undercloud_server}
  undercloud_floating_ip:
    description: "floating ip of the undercloud instance"
    value:
      get_attr: [undercloud_floating_ip, undercloud_floating_ip]
  undercloud_private_ip:
    description: "private cluster ip of the undercloud instance"
    value:
      get_attr:
        - undercloud_server
        - networks
        - {get_param: private_net_cluster1}
        - 0
