heat_template_version: 2015-04-30

parameters:
  undercloud_flavor:
    type: string
  undercloud_image:
    type: string
  key_name:
    type: string
  undercloud_name:
    type: string
  undercloud_user_data:
    type: string
  private_net:
    type: string
  public_net:
    type: string

resources:
  undercloud_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: undercloud_sg
      description: Ping and SSH
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

  undercloud_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: undercloud_flavor}
      image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      networks:
      - network: {get_param: private_net}
      security_groups:
        - "default"
        - {get_resource: undercloud_sg}
      name: {get_param: undercloud_name}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_param: undercloud_user_data}
      software_config_transport: POLL_SERVER_HEAT

  undercloud_floating_ip:
    type: OS::TraaS::UndercloudFloating
    properties:
      public_net: {get_param: public_net}
      undercloud_port:
        get_attr:
          - undercloud_server
          - addresses
          - {get_param: private_net}
          - 0
          - port

  undercloud_swap:
    type: OS::TraaS::Swap
    properties:
      server: {get_resource: undercloud_server}

outputs:
  undercloud_server:
    description: "undercloud server resource"
    value: {get_resource: undercloud_server}
  undercloud_floating_ip:
    description: "floating ip of the undercloud instance"
    value:
      get_attr: [undercloud_floating_ip, undercloud_floating_ip]
  undercloud_private_ip:
    description: "private ip of the undercloud instance"
    value:
      get_attr:
        - undercloud_server
        - networks
        - {get_param: private_net}
        - 0
