parameters:
  overcloud_flavor: m1.large
  overcloud_image: CentOS-7-x86_64-GenericCloud-1708
  key_name: jslagle-rdo-cloud
  private_net: private
  overcloud_node_count: 1
  public_net:  38.145.32.0/22
  undercloud_image: CentOS-7-x86_64-GenericCloud-1708
  undercloud_flavor: m1.large
  toci_jobtype: multinode-1ctlr-featureset010
  zuul_changes: openstack/tripleo-quickstart-extras:516841^openstack/tripleo-common:512875^openstack/tripleo-common:512876^openstack/python-tripleoclient:514701^openstack/tripleo-common:514783^openstack/tripleo-common:514784^openstack/python-tripleoclient:514789^openstack/tripleo-quickstart:514736
